### PR TITLE
Add support for Botan_PATH

### PR DESCRIPTION
**Pull request by NtWriteCode**

### CODE REVIEW

**Comment by Tectu** [comment]
Thanks! This looks pretty good!

Could you factor the CMake policy change out into a separate PR?

**Comment by NtWriteCode** [comment]
@Tectu reverted

**Comment by Tectu** [comment]
Great - Thanks!
I think you did a good job on the `Botan_PATH` feature. However, I'd like to properly test it before merging but it looks good so far!

Feel free to make another PR for the CMake policy - I'll also gladly merge that one :)

**Comment by NtWriteCode** [comment]
Sure, take your time, I'm glad to accept any critics as I'm not too experienced with CMake :)

**Comment by Tectu** [comment]
Looks good to me - thank you for your contribution!

**Pull request merged**
